/**
 * Intelligent drug categorization based on product names and descriptions
 * Maps drugs to appropriate categories from PRODUCT_CATEGORIES
 */

import { PRODUCT_CATEGORIES } from './categories';

// Category keywords mapping
const CATEGORY_KEYWORDS: Record<string, string[]> = {
  'ANALGESICS & ANTI-INFLAMMATORIES (PAINKILLERS)': [
    'paracetamol',
    'acetaminophen',
    'ibuprofen',
    'aspirin',
    'diclofenac',
    'naproxen',
    'ketorolac',
    'tramadol',
    'morphine',
    'codeine',
    'advil',
    'panadol',
    'brufen',
    'voltaren',
    'anacin',
    'tylenol',
    'pain',
    'analgesic',
    'anti-inflammatory',
    'antiinflammatory',
    'dolor',
    'algia',
  ],
  'ANTIPYRETICS (FEVER REDUCERS)': [
    'fever',
    'antipyretic',
    'pyrexia',
    'temperature',
    'hyperthermia',
  ],
  ANTIBIOTICS: [
    'amoxicillin',
    'ampicillin',
    'penicillin',
    'cephalexin',
    'cefuroxime',
    'azithromycin',
    'erythromycin',
    'clindamycin',
    'doxycycline',
    'tetracycline',
    'ciprofloxacin',
    'levofloxacin',
    'metronidazole',
    'trimethoprim',
    'sulfamethoxazole',
    'amikacin',
    'gentamicin',
    'vancomycin',
    'amoksi',
    'amoxi',
    'clav',
    'augmentin',
    'zithromax',
    'bactrim',
    'septra',
  ],
  'ANTIMICROBIALS (NON-ANTIBIOTIC)': [
    'antiseptic',
    'disinfectant',
    'chlorhexidine',
    'povidone',
    'iodine',
    'hydrogen peroxide',
    'alcohol',
    'sanitizer',
  ],
  'ANTI-MALARIALS': [
    'malaria',
    'artemisinin',
    'artemether',
    'lumefantrine',
    'quinine',
    'chloroquine',
    'mefloquine',
    'primaquine',
    'doxycycline',
    'atovaquone',
    'proguanil',
    'coartem',
    'malarone',
    'fansidar',
  ],
  'ANTIPARASITICS (ANTI-WORM MEDICINES)': [
    'albendazole',
    'mebendazole',
    'praziquantel',
    'ivermectin',
    'piperazine',
    'worm',
    'helminth',
    'parasite',
    'deworm',
    'anthelmintic',
  ],
  ANTIVIRALS: [
    'acyclovir',
    'aciclovir',
    'valacyclovir',
    'ganciclovir',
    'oseltamivir',
    'zanamivir',
    'ribavirin',
    'lamivudine',
    'tenofovir',
    'efavirenz',
    'antiviral',
    'herpes',
    'hiv',
    'aids',
    'flu',
    'influenza',
    'tamiflu',
  ],
  ANTIFUNGALS: [
    'fluconazole',
    'ketoconazole',
    'clotrimazole',
    'miconazole',
    'nystatin',
    'amphotericin',
    'griseofulvin',
    'terbinafine',
    'antifungal',
    'fungal',
    'candidiasis',
    'ringworm',
    'tinea',
    'yeast',
  ],
  'GASTROINTESTINAL MEDICINES': [
    'omeprazole',
    'pantoprazole',
    'lansoprazole',
    'ranitidine',
    'cimetidine',
    'famotidine',
    'antacid',
    'gaviscon',
    'maalox',
    'pepcid',
    'prilosec',
    'loperamide',
    'diphenoxylate',
    'metoclopramide',
    'domperidone',
    'ondansetron',
    'granisetron',
    'stomach',
    'gastric',
    'ulcer',
    'reflux',
    'gerd',
    'diarrhea',
    'diarrhoea',
    'nausea',
    'vomit',
    'constipation',
    'laxative',
    'stool',
    'bowel',
  ],
  'CARDIOVASCULAR MEDICINES': [
    'amlodipine',
    'atenolol',
    'metoprolol',
    'propranolol',
    'lisinopril',
    'enalapril',
    'captopril',
    'losartan',
    'valsartan',
    'irbesartan',
    'furosemide',
    'hydrochlorothiazide',
    'spironolactone',
    'digoxin',
    'warfarin',
    'aspirin',
    'clopidogrel',
    'atorvastatin',
    'simvastatin',
    'pravastatin',
    'rosuvastatin',
    'blood pressure',
    'hypertension',
    'heart',
    'cardiac',
    'cholesterol',
    'lipid',
    'anticoagulant',
    'antiplatelet',
    'beta blocker',
    'ace inhibitor',
    'calcium channel',
    'diuretic',
  ],
  'DIABETES MEDICINES': [
    'metformin',
    'glibenclamide',
    'gliclazide',
    'glipizide',
    'insulin',
    'glimepiride',
    'pioglitazone',
    'rosiglitazone',
    'sitagliptin',
    'vildagliptin',
    'diabetes',
    'diabetic',
    'glucose',
    'sugar',
    'glycemic',
    'hypoglycemic',
    'hyperglycemic',
    'insulin',
    'glucagon',
    'amaryl',
    'glucophage',
    'januvia',
  ],
  'RESPIRATORY MEDICINES': [
    'salbutamol',
    'albuterol',
    'ventolin',
    'ipratropium',
    'tiotropium',
    'budesonide',
    'fluticasone',
    'beclomethasone',
    'prednisolone',
    'montelukast',
    'theophylline',
    'aminophylline',
    'asthma',
    'copd',
    'bronchitis',
    'cough',
    'expectorant',
    'mucolytic',
    'decongestant',
    'inhaler',
    'nebulizer',
    'respiratory',
    'breathing',
    'wheeze',
  ],
  'VITAMINS & MINERALS': [
    'vitamin',
    'multivitamin',
    'calcium',
    'iron',
    'zinc',
    'magnesium',
    'folic acid',
    'folate',
    'b12',
    'b complex',
    'vitamin c',
    'vitamin d',
    'vitamin e',
    'vitamin a',
    'mineral',
    'nutrient',
  ],
  'DIETARY OR NUTRITIONAL SUPPLEMENTS': [
    'supplement',
    'dietary',
    'nutritional',
    'omega',
    'fish oil',
    'protein',
    'probiotic',
    'prebiotic',
    'collagen',
    'glucosamine',
    'chondroitin',
    'coenzyme',
    'coq10',
    'q10',
    'antioxidant',
    'resveratrol',
    'turmeric',
    'curcumin',
    'spirulina',
    'chlorella',
    'wheatgrass',
    'barley grass',
    'green tea extract',
    'ginkgo',
    'biloba',
    'ginseng',
    'ashwagandha',
    'rhodiola',
    'maca',
    'moringa',
    'aloe vera',
    'echinacea',
    'elderberry',
    'saw palmetto',
    'milk thistle',
    'dandelion',
    'nettle',
    'valerian',
    'melatonin',
    '5-htp',
    'st john',
    'wort',
    'evening primrose',
    'flaxseed',
    'hemp',
    'cbd',
    'wellness',
    'vital',
    'care',
    'flora',
    'radiance',
    'pregna',
    'procare',
    'ipace',
    'vital seas',
    'vital woman',
    'vital man',
    'vital b',
    'aj wellness',
  ],
  'HORMONAL MEDICATIONS': [
    'estrogen',
    'progesterone',
    'testosterone',
    'thyroid',
    'levothyroxine',
    'contraceptive',
    'birth control',
    'pill',
    'hormone',
    'steroid',
    'prednisone',
    'prednisolone',
    'dexamethasone',
    'hydrocortisone',
    'cortisol',
    'insulin',
    'glucagon',
  ],
  'NEUROLOGICAL & PSYCHIATRIC MEDICINES': [
    'amitriptyline',
    'fluoxetine',
    'sertraline',
    'paroxetine',
    'citalopram',
    'escitalopram',
    'duloxetine',
    'venlafaxine',
    'carbamazepine',
    'phenytoin',
    'valproate',
    'gabapentin',
    'pregabalin',
    'diazepam',
    'lorazepam',
    'alprazolam',
    'clonazepam',
    'haloperidol',
    'risperidone',
    'olanzapine',
    'quetiapine',
    'antidepressant',
    'antipsychotic',
    'anticonvulsant',
    'antiepileptic',
    'anxiolytic',
    'sedative',
    'tranquilizer',
    'mood',
    'depression',
    'anxiety',
    'epilepsy',
    'seizure',
    'bipolar',
    'schizophrenia',
    'adhd',
    'attention',
  ],
  'DERMATOLOGICAL (SKIN) MEDICINES': [
    'hydrocortisone',
    'betamethasone',
    'clobetasol',
    'mometasone',
    'tretinoin',
    'isotretinoin',
    'benzoyl peroxide',
    'salicylic acid',
    'acne',
    'eczema',
    'psoriasis',
    'dermatitis',
    'rash',
    'itch',
    'pruritus',
    'fungal',
    'ringworm',
    'tinea',
    'cream',
    'ointment',
    'topical',
    'skin',
    'dermal',
    'cutaneous',
  ],
  'EYE & EAR PREPARATIONS': [
    'eye',
    'ophthalmic',
    'ocular',
    'ear',
    'otic',
    'aural',
    'drops',
    'solution',
    'ointment',
    'conjunctivitis',
    'glaucoma',
    'cataract',
    'retina',
    'cornea',
    'vision',
    'sight',
    'hearing',
    'auditory',
  ],
  'SPECIALTY INJECTIONS': [
    'injection',
    'injectable',
    'inject',
    'injectable',
    'vial',
    'ampoule',
    'syringe',
    'iv',
    'intravenous',
    'im',
    'intramuscular',
    'subcutaneous',
    'sc',
    'infusion',
    'drip',
  ],
  'IV FLUIDS (INFUSIONS)': [
    'saline',
    'dextrose',
    'glucose',
    'ringer',
    'lactate',
    'infusion',
    'iv fluid',
    'drip',
    'solution',
    'normal saline',
    'ns',
    'ds',
    'd5w',
    'd10w',
    'ringer',
    'hartmann',
  ],
  'ANTIHELMINTICS (Worm medicines)': [
    'albendazole',
    'mebendazole',
    'praziquantel',
    'ivermectin',
    'piperazine',
    'worm',
    'helminth',
    'parasite',
    'deworm',
    'anthelmintic',
  ],
  'OTC (OVER-THE-COUNTER) PRODUCTS': [
    'cough syrup',
    'cold',
    'flu',
    'allergy',
    'antihistamine',
    'nasal',
    'spray',
    'lozenge',
    'throat',
    'sore throat',
    'cough',
    'decongestant',
  ],
  'HERBAL PRODUCTS': [
    'herbal',
    'herb',
    'natural',
    'traditional',
    'ginseng',
    'ginger',
    'turmeric',
    'garlic',
    'aloe',
    'echinacea',
    'echinacea',
    'ginseng',
    'ashwagandha',
    'bitter',
    'tonic',
    'mixture',
  ],
  'MEDICAL CONSUMABLES': [
    'syringe',
    'needle',
    'glove',
    'mask',
    'gauze',
    'bandage',
    'plaster',
    'cotton',
    'swab',
    'alcohol',
    'antiseptic',
    'disinfectant',
    'strip',
    'test',
    'kit',
    'consumable',
    'disposable',
  ],
  'MEDICAL DEVICES': [
    'device',
    'monitor',
    'meter',
    'glucometer',
    'thermometer',
    'bp',
    'blood pressure',
    'stethoscope',
    'brace',
    'support',
    'splint',
    'crutch',
    'wheelchair',
    'walker',
    'cane',
  ],
  'BABY & MATERNAL CARE ITEMS': [
    'baby',
    'infant',
    'pediatric',
    'paediatric',
    'maternal',
    'pregnancy',
    'prenatal',
    'postnatal',
    'lactation',
    'breastfeeding',
    'formula',
    'diaper',
    'nappy',
    'pacifier',
    'soother',
    'bottle',
    'feeding',
  ],
  'HYGIENE & PERSONAL CARE': [
    'soap',
    'shampoo',
    'conditioner',
    'toothpaste',
    'toothbrush',
    'deodorant',
    'antiperspirant',
    'sanitary',
    'pad',
    'tampon',
    'liner',
    'shower',
    'gel',
    'lotion',
    'cream',
    'moisturizer',
    'sunscreen',
    'hygiene',
    'personal care',
    'cosmetic',
    'beauty',
    'skincare',
    'haircare',
  ],
};

/**
 * Categorizes a drug based on its name and description
 */
export function categorizeDrug(name: string, description?: string): string {
  const searchText = `${name} ${description || ''}`.toLowerCase();

  // Score each category based on keyword matches
  const categoryScores: Record<string, number> = {};

  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    let score = 0;
    for (const keyword of keywords) {
      if (searchText.includes(keyword)) {
        score += keyword.length; // Longer keywords get more weight
      }
    }
    if (score > 0) {
      categoryScores[category] = score;
    }
  }

  // Return the category with the highest score
  if (Object.keys(categoryScores).length > 0) {
    const bestCategory = Object.entries(categoryScores).sort(
      (a, b) => b[1] - a[1]
    )[0][0];
    return bestCategory;
  }

  // Default fallback categories based on common patterns
  if (
    name.includes('INF') ||
    name.includes('INFUSION') ||
    name.includes('DEXTROSE') ||
    name.includes('GLUCOSE INF')
  ) {
    return 'IV FLUIDS (INFUSIONS)';
  }

  if (name.includes('INJ') || name.includes('INJECTION')) {
    return 'SPECIALTY INJECTIONS';
  }

  if (name.includes('EYE') || name.includes('OPHTHALMIC')) {
    return 'EYE & EAR PREPARATIONS';
  }

  if (
    name.includes('CREAM') ||
    name.includes('OINTMENT') ||
    name.includes('TOPICAL')
  ) {
    return 'DERMATOLOGICAL (SKIN) MEDICINES';
  }

  if (
    name.includes('SYR') ||
    name.includes('SUSP') ||
    name.includes('MIXTURE')
  ) {
    // Could be various categories, but common ones:
    if (
      name.includes('COUGH') ||
      name.includes('COLD') ||
      name.includes('FLU')
    ) {
      return 'RESPIRATORY MEDICINES';
    }
    if (
      name.includes('BITTER') ||
      name.includes('TONIC') ||
      name.includes('HERBAL')
    ) {
      return 'HERBAL PRODUCTS';
    }
  }

  // Default to OTC if no match found
  return 'OTC (OVER-THE-COUNTER) PRODUCTS';
}
